### ISSUE TITLE
Create basic level

### ISSUE THREAD

**Issue by Techno-Brony** [Johny5134234/BlackHorizons#4]
Create a level for testing various game mechanics.

**Comment by Johny5134234** [comment]
Is this a testing level or a beta level with custom assets and such?

**Comment by Techno-Brony** [comment]
Testing level

> testing various game mechanics

**Comment by Johny5134234** [comment]
K

**Comment by Johny5134234** [comment]
Created basic test level, will expand it as more mechanics are introduced
