### ISSUE TITLE
Fixing infinte jump

### ISSUE THREAD

**Issue by Johny5134234** [Johny5134234/BlackHorizons#7]
Player can jump for infinity right now so a simple jump check method should be introduced

**Comment by Techno-Brony** [comment]
Fixed via #8

**Comment by Techno-Brony** [comment]
There must be something wrong with the code related to checking if the player is on the ground.
`void fixedUpdate() {
		grounded = Physics2D.OverlapCircle (groundCheck.position, groundCheckRadius, whatIsGround);
	}`

**Comment by Johny5134234** [comment]
Solved it
